FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN apt-get update 
RUN mkdir /deploy
WORKDIR /deploy
COPY requirements.txt /deploy/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /deploy/
EXPOSE 8000
CMD python manage.py makemigrations --merge --noinput && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000