# Generated by Django 4.2 on 2023-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvarparam',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='varparam',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
