# Generated by Django 4.1.5 on 2023-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvariant',
            name='parameters_value',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='variant',
            name='parameters_value',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
