# Generated by Django 4.1.5 on 2023-01-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historicalvariant_parameters_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='variant',
            name='categories',
            field=models.ManyToManyField(to='inventory.category'),
        ),
    ]
