# Generated by Django 4.1.5 on 2023-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_category_products_variant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariant',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
