# Generated by Django 4.1.5 on 2023-03-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_historicalvariant_file_variant_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvariant',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
