# Generated by Django 4.1.5 on 2023-03-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_varparams_historicalvarparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvarparams',
            name='variant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.variant'),
        ),
        migrations.AddField(
            model_name='varparams',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.variant'),
        ),
    ]
