# Generated by Django 4.1.5 on 2023-03-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicalvarparams_variant_varparams_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varparams',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.variant'),
        ),
    ]
