# Generated by Django 4.1.5 on 2023-03-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_historicalvarparams_historicalvarparam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvariant',
            name='parameters_value',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='parameters_value',
        ),
    ]
