# Generated by Django 4.2 on 2023-05-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_historicalprofile_email_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='historicalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
