# Generated by Django 4.2 on 2023-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_historicalprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
