# Generated by Django 4.1.5 on 2023-05-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_historicalvarparam_value_alter_varparam_value'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.variant'),
        ),
    ]
